package bookstoredb.entidade2;
// Generated 11 de jun. de 2020 18:24:09 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Avaliacao generated by hbm2java
 */
@Entity
@Table(name = "avaliacao", catalog = "bookstoredb")
public class Avaliacao implements java.io.Serializable {

	private Integer avaliacaoId;
	private Cliente cliente;
	private Livro livro;
	private int classificacao;
	private String manchete;
	private String comentario;
	private Date horaAvaliacao;

	public Avaliacao() {
	}

	public Avaliacao(Cliente cliente, Livro livro, int classificacao, String manchete, String comentario,
			Date horaAvaliacao) {
		this.cliente = cliente;
		this.livro = livro;
		this.classificacao = classificacao;
		this.manchete = manchete;
		this.comentario = comentario;
		this.horaAvaliacao = horaAvaliacao;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "avaliacao_id", unique = true, nullable = false)
	public Integer getAvaliacaoId() {
		return this.avaliacaoId;
	}

	public void setAvaliacaoId(Integer avaliacaoId) {
		this.avaliacaoId = avaliacaoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cliente_id", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "livro_id", nullable = false)
	public Livro getLivro() {
		return this.livro;
	}

	public void setLivro(Livro livro) {
		this.livro = livro;
	}

	@Column(name = "classificacao", nullable = false)
	public int getClassificacao() {
		return this.classificacao;
	}

	public void setClassificacao(int classificacao) {
		this.classificacao = classificacao;
	}

	@Column(name = "manchete", nullable = false, length = 128)
	public String getManchete() {
		return this.manchete;
	}

	public void setManchete(String manchete) {
		this.manchete = manchete;
	}

	@Column(name = "comentario", nullable = false, length = 500)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hora_avaliacao", nullable = false, length = 19)
	public Date getHoraAvaliacao() {
		return this.horaAvaliacao;
	}

	public void setHoraAvaliacao(Date horaAvaliacao) {
		this.horaAvaliacao = horaAvaliacao;
	}

}
